# Generated by Django 2.2 on 2021-09-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id_pokemon', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('special_defense', models.IntegerField()),
                ('special_attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('evolution', models.IntegerField()),
            ],
        ),
    ]
