# Generated by Django 2.2 on 2021-09-27 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionChain',
            fields=[
                ('id_evolution_chain', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name_poke', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id_pokemon', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=255)),
                ('id_evolution_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_api.EvolutionChain')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id_stat', models.IntegerField(primary_key=True, serialize=False)),
                ('special_defense', models.CharField(max_length=255)),
                ('special_attack', models.CharField(max_length=255)),
                ('defense', models.CharField(max_length=255)),
                ('attack', models.CharField(max_length=255)),
                ('hp', models.CharField(max_length=255)),
                ('speed', models.CharField(max_length=255)),
                ('id_pokemon_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_api.Pokemon')),
            ],
        ),
    ]
