# Generated by Django 2.2 on 2021-09-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='attack',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='defense',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='evolution',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='hp',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='special_attack',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='special_defense',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='speed',
            field=models.CharField(max_length=255),
        ),
    ]
