# Generated by Django 2.2 on 2021-09-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_api', '0002_auto_20210922_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='id_pokemon',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
